$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
display_name: random_forest_training_job
code: data-science/src
command: >
  python train.py --train_data ${{inputs.train_data}} --test_data ${{inputs.test_data}} --n_estimators ${{search_space.n_estimators}} --max_depth ${{search_space.max_depth}} --model_output ${{outputs.model_output}}
environment: azureml:used-cars-train-env@latest
inputs:
  train_data: uri_file
  test_data: uri_file
outputs:
  model_output: mlflow_model
